import { StyleSheet } from 'react-native';
import { scale, verticalScale, moderateScale, fontScale } from '../../utils/scaling';
import { commonStyles } from '../../styles/common';

export const styles = StyleSheet.create({
  container: {
    ...commonStyles.container,
  },
  background: {
    ...commonStyles.background,
  },
  overlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  iconShell: {
    position: 'absolute',
    top: verticalScale(90),
    left: scale(32),
    width: moderateScale(62),
    height: moderateScale(62),
    borderRadius: moderateScale(16),
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 5,
    elevation: 8,
  },
  closeButton: {
    position: 'absolute',
    top: verticalScale(90),
    right: scale(32),
    width: moderateScale(62),
    height: moderateScale(62),
    borderRadius: moderateScale(16),
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 10,
    zIndex: 6,
  },
  closeText: {
    fontSize: fontScale(24),
    fontWeight: '700',
    color: '#111111',
  },
  chatCard: {
    width: scale(900),
    flex: 1,
    maxHeight: verticalScale(1750),
    backgroundColor: '#E7E7E7',
    borderRadius: moderateScale(22),
    overflow: 'hidden',
    marginTop: verticalScale(160),
    marginBottom: verticalScale(40),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 6,
    zIndex: 1,
  },
  header: {
    backgroundColor: '#F2F2F2',
    paddingVertical: verticalScale(18),
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: fontScale(26),
    fontWeight: '700',
    color: '#1E1E1E',
  },
  statusRow: {
    backgroundColor: '#DCE7FF',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(24),
    paddingVertical: verticalScale(14),
  },
  statusDot: {
    width: moderateScale(14),
    height: moderateScale(14),
    borderRadius: moderateScale(7),
    backgroundColor: '#22B000',
    marginRight: scale(12),
  },
  statusText: {
    fontSize: fontScale(16),
    fontWeight: '600',
    color: '#1D1D1D',
  },
  messageList: {
    flexGrow: 1,
    paddingHorizontal: scale(24),
    paddingVertical: verticalScale(18),
  },
  messageListContainer: {
    flex: 1,
  },
  loadingState: {
    paddingVertical: verticalScale(20),
    alignItems: 'center',
  },
  messageItem: {
    marginBottom: verticalScale(16),
  },
  messageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  senderBadge: {
    backgroundColor: '#163DFF',
    borderRadius: moderateScale(12),
    paddingHorizontal: scale(14),
    paddingVertical: verticalScale(6),
    marginRight: scale(10),
  },
  senderText: {
    fontSize: fontScale(14),
    fontWeight: '700',
    color: '#FFFFFF',
  },
  timeText: {
    fontSize: fontScale(14),
    fontWeight: '600',
    color: '#6A6A6A',
  },
  messageText: {
    marginTop: verticalScale(8),
    fontSize: fontScale(18),
    color: '#1D1D1D',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(20),
    paddingVertical: verticalScale(14),
    backgroundColor: '#E7E7E7',
  },
  textInput: {
    flex: 1,
    backgroundColor: '#F8F8F8',
    borderRadius: moderateScale(14),
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(8),
    borderWidth: 1,
    borderColor: '#CFCFCF',
    fontSize: fontScale(16),
    color: '#1D1D1D',
  },
  sendButton: {
    marginLeft: scale(12),
    backgroundColor: '#1439FF',
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(10),
    borderRadius: moderateScale(12),
    justifyContent: 'center',
    alignItems: 'center',
  },
  sendButtonDisabled: {
    opacity: 0.6,
  },
  sendButtonText: {
    fontSize: fontScale(16),
    fontWeight: '700',
    color: '#FFFFFF',
  },
});
